name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    # services:
    #   selenium:
    #     image: selenium/standalone-chrome

    steps:
    - uses: actions/checkout@v3
    # - name: wget
    #   uses: wei/wget@v1
    #   with:
    #     args: -qO- https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    
    # - name: extract chrome
    #   run: |
    #     ls -al
    #     sudo dpkg -i ./chrome/google-chrome-stable_current_amd64.deb
  

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./AmazonAutomation
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      working-directory: ./AmazonAutomation
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Application
      working-directory: ./AmazonAutomation
      run: |
        python app.py

