name: Python Application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.12"
    # - name: Install dependencies
    #   working-directory: ./AmazonAutomation
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #     - name: Installing package list
    #     run: apt list --installed    
        
    # - name: Removing previous chrome instances on runner 
    #   run: sudo apt purge google-chrome-stable  
      
    #   # Need to fetch reqs if needed
    # - name: Installing all necessary packages
    #   run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
    # - name: Install xvfb
    #   run: sudo apt-get install xvfb

  
    - name: Build Application
      working-directory: ./AmazonAutomation
      run: |
        python -m venv venv && source venv/bin/activate
        python3 -m pip install -r requirements.txt
        python3 app.py
